### ISSUE TITLE
non-linear progression

### ISSUE THREAD

**Issue by M1cha** [M1cha/hyprctl-custom#1]
Also just want to let you know that hyprctl-custom works great with fusuma:
```
swipe:
  3:
    up:
      update:
        command: "~/.local/bin/hyprctl-custom cursor-zoom in"
    down:
      update:
        command: "~/.local/bin/hyprctl-custom cursor-zoom out"
interval:
  swipe: 0.2
```

I mostly use keyboard and trying to migrate to mouseless (touchpadless) life, but I appreciate the gestures when I am too lazy or just using laptop one handed.

The only thing I am missing is non-linear progression, some curve. Because the more you are zoomed in, the smaller next "step" feels. Hope you understood what I mean. But this already involves some config file I guess, which is not that easy, at least for me. Just my thoughts :)

_Originally posted by @ZerdoX-x in https://github.com/M1cha/dotfiles/issues/1#issuecomment-1720258881_
